# Makefile — build/test/lint facade for pveforge.
#
# This project's real tooling is plain Go (go build, go test, gofmt, go
# vet) — no separate build system to wrap. This facade exists so every
# common task has one name regardless of which tool implements it
# underneath, and so `make` alone is always safe to run (see
# .DEFAULT_GOAL below): it never builds, tests, or installs anything on
# its own.
.DEFAULT_GOAL := help

BINARY  := pveforge
BIN_DIR := bin
PREFIX  ?= $(HOME)/.local

# The actual Go source tree — used to scope gofmt so it never walks
# .git/.claude/.grok/.vibe-palace (gofmt does NOT skip dot-directories on
# its own, confirmed: `gofmt -l .` at the repo root would otherwise
# recurse into all of them for no benefit).
GO_DIRS := cmd internal

# OFFLINE runs a go command read-only and without a module proxy: it can
# neither fetch a module nor edit go.mod/go.sum, so an import that would
# need a new module fails instead of being resolved silently, and a cold
# module cache fails loudly ("run 'go mod download' once, online").
# GOWORK=off: a developer's go.work must not redirect these checks — it
# would resolve the fork to an unpinned local directory. OFFLINE also
# overrides any GOFLAGS the developer has set, for these commands only.
OFFLINE := GOFLAGS=-mod=readonly GOPROXY=off GOWORK=off

# VULNDB, when set, is passed to govulncheck as its vulnerability database
# (-db), e.g. file:///path/to/a/local/mirror for an offline run.
VULNDB ?=

##@ General

.PHONY: help
help: ## Show this help
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) }' $(MAKEFILE_LIST)
	@echo ""
	@echo "Quick start:  make build && make test"

##@ Build

.PHONY: build
build: ## Build the pveforge binary into bin/
	go build -o $(BIN_DIR)/$(BINARY) ./cmd/pveforge

# The pages are generated by a test (cmd/pveforge/man_test.go), so the
# generator and its dependencies never reach the binary. Without
# -update-man that same test is the guard `make test` runs: docs/man must
# match the command tree byte for byte.
.PHONY: man
man: ## Regenerate the man pages in docs/man from the command tree
	go test ./cmd/pveforge -run '^TestManPages$$' -count=1 -update-man

##@ Test

.PHONY: test
test: ## Run unit tests (race detector + coverage — this project's standing verification bar)
	go test ./... -race -cover -count=1 -timeout 20m

.PHONY: check
check: lint test ## Everything CI runs: lint (module hygiene, gofmt, vet) then the unit tests

.PHONY: integration
integration: ## Run integration-tagged tests (none exist yet — this project's live-host verification has so far been manual, ad-hoc SSH probes against a real PVE cluster, never wired into `go test`; kept as a placeholder so a future -tags=integration test file needs no Makefile change)
	@if [ -z "$$(grep -rl --include='*.go' 'go:build integration\|+build integration' $(GO_DIRS) 2>/dev/null)" ]; then \
		echo "no integration-tagged tests exist yet"; \
	else \
		go test -tags=integration ./...; \
	fi

##@ Lint

.PHONY: lint
lint: modcheck ## Check module hygiene (modcheck), formatting (gofmt) and static analysis (go vet) — read-only, fails on any issue
	@fmtfiles="$$(gofmt -l $(GO_DIRS))"; \
	if [ -n "$$fmtfiles" ]; then \
		echo "gofmt: the following files need formatting (run 'make fmt'):"; \
		echo "$$fmtfiles"; \
		exit 1; \
	fi
	$(OFFLINE) go vet ./...

# The module-graph rules the go tool does not enforce (the go-proxmox fork
# pinned to a vX.Y.Z-pveforge.N tag, no replace/exclude, the upstream
# module absent) are a Go test, internal/sourceguard's
# TestModuleGraph_ForkPinnedAndUpstreamAbsent, so `make test` runs them.
.PHONY: modcheck
modcheck: ## Module hygiene, offline and read-only: go.mod/go.sum tidy, go.sum matches the module cache, and everything builds without fetching
	@echo "modcheck: go mod download (cache check)"; $(OFFLINE) go mod download || { echo "modcheck: the module cache is missing modules this module needs; run 'go mod download' once, online"; exit 1; }
	@echo "modcheck: go mod tidy -diff"; $(OFFLINE) go mod tidy -diff || { echo "modcheck: go.mod/go.sum are not tidy (the diff above; run 'go mod tidy' and commit it)"; exit 1; }
	@echo "modcheck: go mod verify"; $(OFFLINE) go mod verify
	@echo "modcheck: offline build"; $(OFFLINE) go build ./...

.PHONY: vuln
vuln: ## Scan for known vulnerabilities with govulncheck (needs its database: online, or VULNDB=file:///mirror) — never part of lint/test
	@command -v govulncheck >/dev/null 2>&1 || { echo "vuln: govulncheck is not installed: go install golang.org/x/vuln/cmd/govulncheck@v1.6.0"; exit 1; }
	govulncheck $(if $(VULNDB),-db $(VULNDB)) ./...

.PHONY: fmt
fmt: ## Reformat all Go source files in place (gofmt -w)
	gofmt -w $(GO_DIRS)

##@ Install

# -Dm755 relies on GNU coreutils' install (the -D flag that creates
# leading directories is a GNU extension, absent from BSD/macOS's native
# install) — accepted, not fixed: this project's realistic deployment
# target is Linux, matching the PVE hypervisor hosts it manages.
.PHONY: install
# install copies docs/man/*.1 over what is there; it never removes the page
# of a command that has since been deleted — remove that one by hand.
install: build ## Build and install to PREFIX (default: ~/.local), with the man pages
	install -Dm755 $(BIN_DIR)/$(BINARY) $(PREFIX)/bin/$(BINARY)
	install -Dm644 -t $(PREFIX)/share/man/man1 docs/man/*.1

##@ Clean

.PHONY: clean
clean: ## Remove build artifacts
	rm -rf $(BIN_DIR)
