.nh
.TH "PVEFORGE" "1" "Sep 2026" "pveforge" "pveforge manual"

.SH NAME
pveforge-completion - Generate the autocompletion script for the specified shell


.SH SYNOPSIS
\fBpveforge completion [flags]\fP


.SH DESCRIPTION
Generate the autocompletion script for pveforge for the specified shell.
See each sub-command's help for details on how to use the generated script.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for completion


.SH SEE ALSO
\fBpveforge(1)\fP, \fBpveforge-completion-bash(1)\fP, \fBpveforge-completion-fish(1)\fP, \fBpveforge-completion-powershell(1)\fP, \fBpveforge-completion-zsh(1)\fP
