.nh
.TH "PVEFORGE" "1" "Sep 2026" "pveforge" "pveforge manual"

.SH NAME
pveforge-roster-validate - Parse and validate the roster file


.SH SYNOPSIS
\fBpveforge roster validate [path] [flags]\fP


.SH DESCRIPTION
Parse and validate the roster file


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for validate


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--roster\fP=""
	path to the roster file (overrides PVEFORGE_ROSTER and the default ./pveforge.toml)


.SH SEE ALSO
\fBpveforge-roster(1)\fP
