.nh
.TH "PVEFORGE" "1" "Sep 2026" "pveforge" "pveforge manual"

.SH NAME
pveforge-discover - Describe PVE's own object schema (layer 1) or a pveforge device type (layer 2)


.SH SYNOPSIS
\fBpveforge discover [flags]\fP


.SH DESCRIPTION
Describe PVE's own object schema (layer 1) or a pveforge device type (layer 2)


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for discover


.SH SEE ALSO
\fBpveforge(1)\fP, \fBpveforge-discover-device(1)\fP, \fBpveforge-discover-network(1)\fP, \fBpveforge-discover-node(1)\fP, \fBpveforge-discover-storage(1)\fP, \fBpveforge-discover-vm(1)\fP
