.nh
.TH "PVEFORGE" "1" "Sep 2026" "pveforge" "pveforge manual"

.SH NAME
pveforge-network - Inspect node-level network interfaces


.SH SYNOPSIS
\fBpveforge network [flags]\fP


.SH DESCRIPTION
Inspect node-level network interfaces


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for network


.SH SEE ALSO
\fBpveforge(1)\fP, \fBpveforge-network-bridge(1)\fP, \fBpveforge-network-get(1)\fP, \fBpveforge-network-set(1)\fP
