.nh
.TH "PVEFORGE" "1" "Sep 2026" "pveforge" "pveforge manual"

.SH NAME
pveforge-api - Raw PVE REST API passthrough for paths with no dedicated command yet


.SH SYNOPSIS
\fBpveforge api [flags]\fP


.SH DESCRIPTION
Raw PVE REST API passthrough for paths with no dedicated command yet


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for api


.SH SEE ALSO
\fBpveforge(1)\fP, \fBpveforge-api-delete(1)\fP, \fBpveforge-api-get(1)\fP, \fBpveforge-api-post(1)\fP, \fBpveforge-api-put(1)\fP
