.nh
.TH "PVEFORGE" "1" "Sep 2026" "pveforge" "pveforge manual"

.SH NAME
pveforge-acl - Grant PVE ACL entries (written as root over SSH)


.SH SYNOPSIS
\fBpveforge acl [flags]\fP


.SH DESCRIPTION
Grant PVE ACL entries (written as root over SSH)


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for acl


.SH SEE ALSO
\fBpveforge(1)\fP, \fBpveforge-acl-grant(1)\fP
