.nh
.TH "PVEFORGE" "1" "Sep 2026" "pveforge" "pveforge manual"

.SH NAME
pveforge-roster - Inspect and initialize the target roster file


.SH SYNOPSIS
\fBpveforge roster [flags]\fP


.SH DESCRIPTION
Inspect and initialize the target roster file


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for roster

.PP
\fB--roster\fP=""
	path to the roster file (overrides PVEFORGE_ROSTER and the default ./pveforge.toml)


.SH SEE ALSO
\fBpveforge(1)\fP, \fBpveforge-roster-import-token(1)\fP, \fBpveforge-roster-init(1)\fP, \fBpveforge-roster-validate(1)\fP
