.nh
.TH "PVEFORGE" "1" "Sep 2026" "pveforge" "pveforge manual"

.SH NAME
pveforge-completion-bash - Generate the autocompletion script for bash


.SH SYNOPSIS
\fBpveforge completion bash\fP


.SH DESCRIPTION
Generate the autocompletion script for the bash shell.

.PP
This script depends on the 'bash-completion' package.
If it is not installed already, you can install it via your OS's package manager.

.PP
To load completions in your current shell session:

.EX
source <(pveforge completion bash)
.EE

.PP
To load completions for every new session, execute once:

.SS Linux:
.EX
pveforge completion bash > /etc/bash_completion.d/pveforge
.EE

.SS macOS:
.EX
pveforge completion bash > $(brew --prefix)/etc/bash_completion.d/pveforge
.EE

.PP
You will need to start a new shell for this setup to take effect.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for bash

.PP
\fB--no-descriptions\fP[=false]
	disable completion descriptions


.SH SEE ALSO
\fBpveforge-completion(1)\fP
