.nh
.TH "PVEFORGE" "1" "Sep 2026" "pveforge" "pveforge manual"

.SH NAME
pveforge-storage-get - Get one storage backend's status


.SH SYNOPSIS
\fBpveforge storage get <target-id> <storage-name> [flags]\fP


.SH DESCRIPTION
Get one storage backend's status


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for get

.PP
\fB--lock-wait\fP=0s
	how long to wait for another pveforge process's lock on this object before giving up (0 = the 15m0s default; at most 1h0m0s). The default exceeds the 10m0s ceiling on waiting for a PVE task because a legitimate lock holder may be in such a wait the whole time

.PP
\fB-o\fP, \fB--output\fP="kv"
	output format: "kv" or "json"

.PP
\fB--roster\fP=""
	path to the roster file (overrides PVEFORGE_ROSTER and the default ./pveforge.toml)


.SH SEE ALSO
\fBpveforge-storage(1)\fP
