.nh
.TH "PVEFORGE" "1" "Sep 2026" "pveforge" "pveforge manual"

.SH NAME
pveforge-vm - Inspect and modify VMs


.SH SYNOPSIS
\fBpveforge vm [flags]\fP


.SH DESCRIPTION
Inspect and modify VMs


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for vm


.SH SEE ALSO
\fBpveforge(1)\fP, \fBpveforge-vm-create(1)\fP, \fBpveforge-vm-get(1)\fP, \fBpveforge-vm-set(1)\fP
