.nh
.TH "PVEFORGE" "1" "Sep 2026" "pveforge" "pveforge manual"

.SH NAME
pveforge-access - Read PVE's users, groups and ACLs (as root over SSH)


.SH SYNOPSIS
\fBpveforge access [flags]\fP


.SH DESCRIPTION
Read PVE's users, groups and ACLs (as root over SSH)


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for access


.SH SEE ALSO
\fBpveforge(1)\fP, \fBpveforge-access-inventory(1)\fP
