.nh
.TH "PVEFORGE" "1" "Sep 2026" "pveforge" "pveforge manual"

.SH NAME
pveforge-group - Ensure PVE groups (written as root over SSH)


.SH SYNOPSIS
\fBpveforge group [flags]\fP


.SH DESCRIPTION
Ensure PVE groups (written as root over SSH)


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for group


.SH SEE ALSO
\fBpveforge(1)\fP, \fBpveforge-group-ensure(1)\fP
