.nh
.TH "PVEFORGE" "1" "Sep 2026" "pveforge" "pveforge manual"

.SH NAME
pveforge-vm-snapshot - List, create, delete and roll back VM snapshots


.SH SYNOPSIS
\fBpveforge vm snapshot [flags]\fP


.SH DESCRIPTION
List, create, delete and roll back VM snapshots


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for snapshot


.SH SEE ALSO
\fBpveforge-vm(1)\fP, \fBpveforge-vm-snapshot-create(1)\fP, \fBpveforge-vm-snapshot-delete(1)\fP, \fBpveforge-vm-snapshot-list(1)\fP, \fBpveforge-vm-snapshot-rollback(1)\fP
