.nh
.TH "PVEFORGE" "1" "Sep 2026" "pveforge" "pveforge manual"

.SH NAME
pveforge - Proxmox VE cluster lifecycle management


.SH SYNOPSIS
\fBpveforge [flags]\fP


.SH DESCRIPTION
Proxmox VE cluster lifecycle management


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for pveforge


.SH SEE ALSO
\fBpveforge-api(1)\fP, \fBpveforge-bootstrap(1)\fP, \fBpveforge-completion(1)\fP, \fBpveforge-discover(1)\fP, \fBpveforge-network(1)\fP, \fBpveforge-node(1)\fP, \fBpveforge-roster(1)\fP, \fBpveforge-schema(1)\fP, \fBpveforge-storage(1)\fP, \fBpveforge-vm(1)\fP
