.nh
.TH "PVEFORGE" "1" "Sep 2026" "pveforge" "pveforge manual"

.SH NAME
pveforge-storage - Inspect storage backends


.SH SYNOPSIS
\fBpveforge storage [flags]\fP


.SH DESCRIPTION
Inspect storage backends


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for storage


.SH SEE ALSO
\fBpveforge(1)\fP, \fBpveforge-storage-get(1)\fP, \fBpveforge-storage-orphans(1)\fP
