.nh
.TH "PVEFORGE" "1" "Sep 2026" "pveforge" "pveforge manual"

.SH NAME
pveforge-network-bridge - Create or destroy a node-level network bridge (two-phase stage/commit)


.SH SYNOPSIS
\fBpveforge network bridge [flags]\fP


.SH DESCRIPTION
Create or destroy a node-level network bridge (two-phase stage/commit)


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for bridge


.SH SEE ALSO
\fBpveforge-network(1)\fP, \fBpveforge-network-bridge-create(1)\fP, \fBpveforge-network-bridge-destroy(1)\fP
